package plugins.faubin.cytomine.module.main;

import be.cytomine.client.Cytomine;
import plugins.faubin.cytomine.utils.Config;
import icy.plugin.abstract_.PluginActionable;

public class Devihm extends PluginActionable {

	@Override
	public void run() {
		// TODO Auto-generated by Icy4Eclipse
		Config.initialize();
		
		IcytomineFrame.cytomine = new Cytomine("http://cytomine.web.pasteur.fr", "d42e7fe6-4e84-4c04-82f5-9863d10d590e", "d22a6cd4-04cb-4d06-8a46-082379219b4c");
		IcytomineFrame frame = IcytomineFrame.getIcytomineFrame();
		
		frame.setVisible(true);
		
	}

}
